### ISSUE TITLE
sed: can't read /etc/rc.local: No such file or directory

### ISSUE THREAD

**Issue by codeclinic** [geekworm-com/x730-script#8]
When I run the script on a Pi4B with Debian I get these issues:

    # sudo bash x730.sh
    sed: can't read /etc/rc.local: No such file or directory
    sed: can't read /etc/rc.local: No such file or directory
    sed: can't read /etc/rc.local: No such file or directory

Any idea how I can fix this?

**Comment by ghost** [comment]
Apologies for necroposting.Your `rc.local` file is missing, as stream editor (`sed`) reported. You may create one yourself, but it is more favourable to configure systemd to launch `/etc/x730pwr.sh` at boot.
Add your own `.service` in `/etc/systemd/system` and have it execute `/etc/x730pwr.sh &` after `boot-complete.target` or thereafter.

Like any custom service, enable it via 'sudo systemctl enable <name>'.

**Comment by codeclinic** [comment]
Thanks for the response. I did figure out a way to get it working... about 13 months ago. ;-)
